# Copyright 2021 san kim
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_NE_TAGS = [
  'PS', # PERSON
  'LC', # LOCATION
  'OG', # ORGANIZATION
  'DT', # DATE
  'TI', # TIME
  'QT', # QUANTITY
  'AF', # ARTIFACT
  'CV', # CIVILIZATION
  'AM', # ANIMAL
  'PT', # PLANT
  'FD', # STUDY_FIELD
  'TR', # THEORY
  'EV', # EVENT
  'MT', # MATERIAL
  'TM' # TERM
]

_NE_IOB2_TAGS = [
    'O',
    'B-PS', # PERSON
    'I-PS', # PERSON
    'B-LC', # LOCATION
    'I-LC', # LOCATION
    'B-OG', # ORGANIZATION
    'I-OG', # ORGANIZATION
    'B-DT', # DATE
    'I-DT', # DATE
    'B-TI', # TIME
    'I-TI', # TIME
    'B-QT', # QUANTITY
    'I-QT', # QUANTITY
    'B-AF', # ARTIFACT
    'I-AF', # ARTIFACT
    'B-CV', # CIVILIZATION
    'I-CV', # CIVILIZATION
    'B-AM', # ANIMAL
    'I-AM', # ANIMAL
    'B-PT', # PLANT
    'I-PT', # PLANT
    'B-FD', # STUDY_FIELD
    'I-FD', # STUDY_FIELD
    'B-TR', # THEORY
    'I-TR', # THEORY
    'B-EV', # EVENT
    'I-EV', # EVENT
    'B-MT', # MATERIAL
    'I-MT', # MATERIAL
    'B-TM' # TERM
    'I-TM' # TERM
]

_COLA_CLASSES = ["unacceptable", "acceptable"]


_NE2020_TAGS = [
    "PS_NAME", 
    "PS_CHARACTER", 
    "PS_PET", 
    "FD_SCIENCE", 
    "FD_SOCIAL_SCIENCE", 
    "FD_MEDICINE", 
    "FD_ART", 
    "FD_HUMANITIES", 
    "FD_OTHERS", 
    "TR_SCIENCE", 
    "TR_SOCIAL_SCIENCE", 
    "TR_MEDICINE", 
    "TR_ART", 
    "TR_HUMANITIES", 
    "TR_OTHERS", 
    "AF_BUILDING", 
    "AF_CULTURAL_ASSET", 
    "AF_ROAD", 
    "AF_TRANSPORT",
    "AF_MUSICAL_INSTRUMENT", 
    "AF_WEAPON", 
    "AFA_DOCUMENT",
    "AFA_PERFORMANCE", 
    "AFA_VIDEO", 
    "AFA_ART_CRAFT", 
    "AFA_MUSIC",
    "AFW_SERVICE_PRODUCTS", 
    "AFW_OTHER_PRODUCTS",
    "OGG_ECONOMY", 
    "OGG_EDUCATION", 
    "OGG_MILITARY", 
    "OGG_MEDIA",
    "OGG_SPORTS", 
    "OGG_ART", 
    "OGG_MEDICINE", 
    "OGG_RELIGION", 
    "OGG_SCIENCE",
    "OGG_LIBRARY", 
    "OGG_LAW", 
    "OGG_POLITICS", 
    "OGG_FOOD", 
    "OGG_HOTEL",
    "OGG_OTHERS",
    "LCP_COUNTRY", 
    "LCP_PROVINCE", 
    "LCP_COUNTY", 
    "LCP_CITY", 
    "LCP_CAPITALCITY",
    "LCG_RIVER", 
    "LCG_OCEAN", 
    "LCG_BAY", 
    "LCG_MOUNTAIN", 
    "LCG_ISLAND",
    "LCG_CONTINENT", 
    "LC_SPACE", 
    "LC_OTHERS",
    "CV_CULTURE", 
    "CV_TRIBE", 
    "CV_LANGUAGE", 
    "CV_POLICY", 
    "CV_LAW",
    "CV_CURRENCY", 
    "CV_TAX", 
    "CV_FUNDS", 
    "CV_ART", 
    "CV_SPORTS",
    "CV_SPORTS_POSITION", 
    "CV_SPORTS_INST", 
    "CV_PRIZE", 
    "CV_RELATION",
    "CV_OCCUPATION", 
    "CV_POSITION", 
    "CV_FOOD", 
    "CV_DRINK", 
    "CV_FOOD_STYLE",
    "CV_CLOTHING", 
    "CV_BUILDING_TYPE",
    "DT_DURATION", 
    "DT_DAY", 
    "DT_WEEK", 
    "DT_MONTH", 
    "DT_YEAR", 
    "DT_SEASON",
    "DT_GEOAGE", 
    "DT_DYNASTY", 
    "DT_OTHERS",
    "TI_DURATION", 
    "TI_HOUR", 
    "TI_MINUTE", 
    "TI_SECOND", 
    "TI_OTHERS",
    "QT_AGE", 
    "QT_SIZE", 
    "QT_LENGTH", 
    "QT_COUNT", 
    "QT_MAN_COUNT", 
    "QT_WEIGHT",
    "QT_PERCENTAGE", 
    "QT_SPEED", 
    "QT_TEMPERATURE", 
    "QT_VOLUME", 
    "QT_ORDER",
    "QT_PRICE", 
    "QT_PHONE", 
    "QT_SPORTS", 
    "QT_CHANNEL", 
    "QT_ALBUM", 
    "QT_ADDRESS",
    "QT_OTHERS",
    "EV_ACTIVITY", 
    "EV_WAR_REVOLUTION", 
    "EV_SPORTS", 
    "EV_FESTIVAL",
    "EV_OTHERS",
    "AM_INSECT", 
    "AM_BIRD", 
    "AM_FISH", 
    "AM_MAMMALIA", 
    "AM_AMPHIBIA",
    "AM_REPTILIA", 
    "AM_TYPE", 
    "AM_PART", 
    "AM_OTHERS",
    "PT_FRUIT", 
    "PT_FLOWER", 
    "PT_TREE", 
    "PT_GRASS", 
    "PT_TYPE", 
    "PT_PART", 
    "PT_OTHERS",
    "MT_ELEMENT", 
    "MT_METAL", 
    "MT_ROCK", 
    "MT_CHEMICAL",
    "TM_COLOR", 
    "TM_DIRECTION", 
    "TM_CLIMATE", 
    "TM_SHAPE",
    "TM_CELL_TISSUE_ORGAN", 
    "TMM_DISEASE", 
    "TMM_DRUG", 
    "TMI_HW", 
    "TMI_SW",
    "TMI_SITE", 
    "TMI_EMAIL", 
    "TMI_MODEL", 
    "TMI_SERVICE", 
    "TMI_PROJECT",
    "TMIG_GENRE", 
    "TM_SPORTS"
]

_NE2020_IOB2_TAGS = [
    "O",
    "B-PS_NAME",
    "I-PS_NAME", 
    "B-PS_CHARACTER",
    "I-PS_CHARACTER", 
    "B-PS_PET",
    "I-PS_PET", 
    "B-FD_SCIENCE",
    "I-FD_SCIENCE", 
    "B-FD_SOCIAL_SCIENCE",
    "I-FD_SOCIAL_SCIENCE", 
    "B-FD_MEDICINE",
    "I-FD_MEDICINE", 
    "B-FD_ART",
    "I-FD_ART", 
    "B-FD_HUMANITIES",
    "I-FD_HUMANITIES", 
    "B-FD_OTHERS",
    "I-FD_OTHERS", 
    "B-TR_SCIENCE",
    "I-TR_SCIENCE", 
    "B-TR_SOCIAL_SCIENCE",
    "I-TR_SOCIAL_SCIENCE", 
    "B-TR_MEDICINE",
    "I-TR_MEDICINE", 
    "B-TR_ART",
    "I-TR_ART", 
    "B-TR_HUMANITIES",
    "I-TR_HUMANITIES", 
    "B-TR_OTHERS",
    "I-TR_OTHERS", 
    "B-AF_BUILDING",
    "I-AF_BUILDING", 
    "B-AF_CULTURAL_ASSET",
    "I-AF_CULTURAL_ASSET", 
    "B-AF_ROAD",
    "I-AF_ROAD", 
    "B-AF_TRANSPORT",
    "I-AF_TRANSPORT",
    "B-AF_MUSICAL_INSTRUMENT",
    "I-AF_MUSICAL_INSTRUMENT", 
    "B-AF_WEAPON",
    "I-AF_WEAPON", 
    "B-AFA_DOCUMENT",
    "I-AFA_DOCUMENT",
    "B-AFA_PERFORMANCE",
    "I-AFA_PERFORMANCE", 
    "B-AFA_VIDEO",
    "I-AFA_VIDEO", 
    "B-AFA_ART_CRAFT",
    "I-AFA_ART_CRAFT", 
    "B-AFA_MUSIC",
    "I-AFA_MUSIC",
    "B-AFW_SERVICE_PRODUCTS",
    "I-AFW_SERVICE_PRODUCTS", 
    "B-AFW_OTHER_PRODUCTS",
    "I-AFW_OTHER_PRODUCTS",
    "B-OGG_ECONOMY",
    "I-OGG_ECONOMY", 
    "B-OGG_EDUCATION",
    "I-OGG_EDUCATION", 
    "B-OGG_MILITARY",
    "I-OGG_MILITARY", 
    "B-OGG_MEDIA",
    "I-OGG_MEDIA",
    "B-OGG_SPORTS",
    "I-OGG_SPORTS", 
    "B-OGG_ART",
    "I-OGG_ART", 
    "B-OGG_MEDICINE",
    "I-OGG_MEDICINE", 
    "B-OGG_RELIGION",
    "I-OGG_RELIGION", 
    "B-OGG_SCIENCE",
    "I-OGG_SCIENCE",
    "B-OGG_LIBRARY",
    "I-OGG_LIBRARY", 
    "B-OGG_LAW",
    "I-OGG_LAW", 
    "B-OGG_POLITICS",
    "I-OGG_POLITICS", 
    "B-OGG_FOOD",
    "I-OGG_FOOD", 
    "B-OGG_HOTEL",
    "I-OGG_HOTEL",
    "B-OGG_OTHERS",
    "I-OGG_OTHERS",
    "B-LCP_COUNTRY",
    "I-LCP_COUNTRY", 
    "B-LCP_PROVINCE",
    "I-LCP_PROVINCE", 
    "B-LCP_COUNTY",
    "I-LCP_COUNTY", 
    "B-LCP_CITY",
    "I-LCP_CITY", 
    "B-LCP_CAPITALCITY",
    "I-LCP_CAPITALCITY",
    "B-LCG_RIVER",
    "I-LCG_RIVER", 
    "B-LCG_OCEAN",
    "I-LCG_OCEAN", 
    "B-LCG_BAY",
    "I-LCG_BAY", 
    "B-LCG_MOUNTAIN",
    "I-LCG_MOUNTAIN", 
    "B-LCG_ISLAND",
    "I-LCG_ISLAND",
    "B-LCG_CONTINENT",
    "I-LCG_CONTINENT", 
    "B-LC_SPACE",
    "I-LC_SPACE", 
    "B-LC_OTHERS",
    "I-LC_OTHERS",
    "B-CV_CULTURE",
    "I-CV_CULTURE", 
    "B-CV_TRIBE",
    "I-CV_TRIBE", 
    "B-CV_LANGUAGE",
    "I-CV_LANGUAGE", 
    "B-CV_POLICY",
    "I-CV_POLICY", 
    "B-CV_LAW",
    "I-CV_LAW",
    "B-CV_CURRENCY",
    "I-CV_CURRENCY", 
    "B-CV_TAX",
    "I-CV_TAX", 
    "B-CV_FUNDS",
    "I-CV_FUNDS", 
    "B-CV_ART",
    "I-CV_ART", 
    "B-CV_SPORTS",
    "I-CV_SPORTS",
    "B-CV_SPORTS_POSITION",
    "I-CV_SPORTS_POSITION", 
    "B-CV_SPORTS_INST",
    "I-CV_SPORTS_INST", 
    "B-CV_PRIZE",
    "I-CV_PRIZE", 
    "B-CV_RELATION",
    "I-CV_RELATION",
    "B-CV_OCCUPATION",
    "I-CV_OCCUPATION", 
    "B-CV_POSITION",
    "I-CV_POSITION", 
    "B-CV_FOOD",
    "I-CV_FOOD", 
    "B-CV_DRINK",
    "I-CV_DRINK", 
    "B-CV_FOOD_STYLE",
    "I-CV_FOOD_STYLE",
    "B-CV_CLOTHING",
    "I-CV_CLOTHING", 
    "B-CV_BUILDING_TYPE",
    "I-CV_BUILDING_TYPE",
    "B-DT_DURATION",
    "I-DT_DURATION", 
    "B-DT_DAY",
    "I-DT_DAY", 
    "B-DT_WEEK",
    "I-DT_WEEK", 
    "B-DT_MONTH",
    "I-DT_MONTH", 
    "B-DT_YEAR",
    "I-DT_YEAR", 
    "B-DT_SEASON",
    "I-DT_SEASON",
    "B-DT_GEOAGE",
    "I-DT_GEOAGE", 
    "B-DT_DYNASTY",
    "I-DT_DYNASTY", 
    "B-DT_OTHERS",
    "I-DT_OTHERS",
    "B-TI_DURATION",
    "I-TI_DURATION", 
    "B-TI_HOUR",
    "I-TI_HOUR", 
    "B-TI_MINUTE",
    "I-TI_MINUTE", 
    "B-TI_SECOND",
    "I-TI_SECOND", 
    "B-TI_OTHERS",
    "I-TI_OTHERS",
    "B-QT_AGE",
    "I-QT_AGE", 
    "B-QT_SIZE",
    "I-QT_SIZE", 
    "B-QT_LENGTH",
    "I-QT_LENGTH", 
    "B-QT_COUNT",
    "I-QT_COUNT", 
    "B-QT_MAN_COUNT",
    "I-QT_MAN_COUNT", 
    "B-QT_WEIGHT",
    "I-QT_WEIGHT",
    "B-QT_PERCENTAGE",
    "I-QT_PERCENTAGE", 
    "B-QT_SPEED",
    "I-QT_SPEED", 
    "B-QT_TEMPERATURE",
    "I-QT_TEMPERATURE", 
    "B-QT_VOLUME",
    "I-QT_VOLUME", 
    "B-QT_ORDER",
    "I-QT_ORDER",
    "B-QT_PRICE",
    "I-QT_PRICE", 
    "B-QT_PHONE",
    "I-QT_PHONE", 
    "B-QT_SPORTS",
    "I-QT_SPORTS", 
    "B-QT_CHANNEL",
    "I-QT_CHANNEL", 
    "B-QT_ALBUM",
    "I-QT_ALBUM", 
    "B-QT_ADDRESS",
    "I-QT_ADDRESS",
    "B-QT_OTHERS",
    "I-QT_OTHERS",
    "B-EV_ACTIVITY",
    "I-EV_ACTIVITY", 
    "B-EV_WAR_REVOLUTION",
    "I-EV_WAR_REVOLUTION", 
    "B-EV_SPORTS",
    "I-EV_SPORTS", 
    "B-EV_FESTIVAL",
    "I-EV_FESTIVAL",
    "B-EV_OTHERS",
    "I-EV_OTHERS",
    "B-AM_INSECT",
    "I-AM_INSECT", 
    "B-AM_BIRD",
    "I-AM_BIRD", 
    "B-AM_FISH",
    "I-AM_FISH", 
    "B-AM_MAMMALIA",
    "I-AM_MAMMALIA", 
    "B-AM_AMPHIBIA",
    "I-AM_AMPHIBIA",
    "B-AM_REPTILIA",
    "I-AM_REPTILIA", 
    "B-AM_TYPE",
    "I-AM_TYPE", 
    "B-AM_PART",
    "I-AM_PART", 
    "B-AM_OTHERS",
    "I-AM_OTHERS",
    "B-PT_FRUIT",
    "I-PT_FRUIT", 
    "B-PT_FLOWER",
    "I-PT_FLOWER", 
    "B-PT_TREE",
    "I-PT_TREE", 
    "B-PT_GRASS",
    "I-PT_GRASS", 
    "B-PT_TYPE",
    "I-PT_TYPE", 
    "B-PT_PART",
    "I-PT_PART", 
    "B-PT_OTHERS",
    "I-PT_OTHERS",
    "B-MT_ELEMENT",
    "I-MT_ELEMENT", 
    "B-MT_METAL",
    "I-MT_METAL", 
    "B-MT_ROCK",
    "I-MT_ROCK", 
    "B-MT_CHEMICAL",
    "I-MT_CHEMICAL",
    "B-TM_COLOR",
    "I-TM_COLOR", 
    "B-TM_DIRECTION",
    "I-TM_DIRECTION", 
    "B-TM_CLIMATE",
    "I-TM_CLIMATE", 
    "B-TM_SHAPE",
    "I-TM_SHAPE",
    "B-TM_CELL_TISSUE_ORGAN",
    "I-TM_CELL_TISSUE_ORGAN", 
    "B-TMM_DISEASE",
    "I-TMM_DISEASE", 
    "B-TMM_DRUG",
    "I-TMM_DRUG", 
    "B-TMI_HW",
    "I-TMI_HW", 
    "B-TMI_SW",
    "I-TMI_SW",
    "B-TMI_SITE",
    "I-TMI_SITE", 
    "B-TMI_EMAIL",
    "I-TMI_EMAIL", 
    "B-TMI_MODEL",
    "I-TMI_MODEL", 
    "B-TMI_SERVICE",
    "I-TMI_SERVICE", 
    "B-TMI_PROJECT",
    "I-TMI_PROJECT",
    "B-TMIG_GENRE",
    "I-TMIG_GENRE", 
    "B-TM_SPORTS",
    "I-TM_SPORTS"
]

NIKL_META={
    'ne_tags': _NE_TAGS,
    'ne_iob2_tabs': _NE_IOB2_TAGS,
    'cola_classes': _COLA_CLASSES,
    'ne2020_tags': _NE2020_TAGS,
    'ne2020_iob2_tabs': _NE2020_IOB2_TAGS,
}